### ISSUE TITLE
Update for python 3.7 ?

### ISSUE THREAD

**Issue by MatevzKu** [m-weigand/ccd_tools#11]
Hi!
I was successfully using your  in my previous research based in python 3.6.
Recently I had to update to 3.7 since the main circuit simulator required this. When I tried to install your package via pip I get the following:

ERROR: Cannot install ccd-tools==0.8.10, ccd-tools==0.8.11, ccd-tools==0.8.12, ccd-tools==0.8.14, ccd-tools==0.8.15, ccd-tools==0.8.16, ccd-tools==0.8.17, ccd-tools==0.8.4, ccd-tools==0.8.5, ccd-tools==0.8.6, ccd-tools==0.8.7, ccd-tools==0.8.8 and ccd-tools==0.8.9 because these package versions have conflicting dependencies.

The conflict is caused by:
    ccd-tools 0.8.17 depends on sip-models
    ccd-tools 0.8.16 depends on sip-models
    ccd-tools 0.8.15 depends on sip_models
    ccd-tools 0.8.14 depends on sip_models
    ccd-tools 0.8.12 depends on sip_models
    ccd-tools 0.8.11 depends on sip_models
    ccd-tools 0.8.10 depends on sip_models
    ccd-tools 0.8.9 depends on sip_models
    ccd-tools 0.8.8 depends on sip_models
    ccd-tools 0.8.7 depends on sip_models
    ccd-tools 0.8.6 depends on sip_models
    ccd-tools 0.8.5 depends on sip_models
    ccd-tools 0.8.4 depends on sip_models

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

Upon viewing your setup.py file I suspect that you last version works in 3.6 and not in 3.7.
Any chance of an update?

Cheers!

**Comment by m-weigand** [comment]
Hi there,
could you give me a bit more information on your environment?
I quick check on Debian with Python 3.9 in a new virtualenv turned out ok, I could just pip install ccd_tools and installation was successful.
thanks and cheers

**Comment by MatevzKu** [comment]
I'm using anaconda as my base.
Python 3.7 with added pyqt 5 and pyopus packages.
When doing the pip install ccd-tools I get the errors I posted above.

Interestingly enough - I tried the same command in 3.8 conda environment and it compiled without trouble. Perhaps this is 3.7 specific?

**Comment by m-weigand** [comment]
Strange, the problem is that I don't have a Python 3.7 environment here to test this and am unsure what to do. From what I see there are no hard dependencies that prevent Python 3.7 from working - only the metadata is out of date in the setup.py.

Could you try installing the sip_models package by hand in the 3.7 environment?

pip install sip_models

**Comment by MatevzKu** [comment]
(py37) C:\Users\matev>pip install sip_models
Collecting sip_models
  Using cached sip_models-0.1.2.tar.gz (9.7 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Anaconda3\envs\py37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\matev\\AppData\\Local\\Temp\\pip-install-xn6yg43f\\sip-models_28583f9419af485c9f0263e512e7aabd\\setup.py'"'"'; __file__='"'"'C:\\Users\\matev\\AppData\\Local\\Temp\\pip-install-xn6yg43f\\sip-models_28583f9419af485c9f0263e512e7aabd\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\matev\AppData\Local\Temp\pip-pip-egg-info-9awk9u9_'
         cwd: C:\Users\matev\AppData\Local\Temp\pip-install-xn6yg43f\sip-models_28583f9419af485c9f0263e512e7aabd\
    Complete output (2 lines):
    error in sip_models setup command: use_2to3 is invalid.
    V3
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/ee/d2/6750c7b55a1166955fbbf9373ce560f227d3dfcced82b3acc6fe7590bbff/sip_models-0.1.2.tar.gz#sha256=0e8ed4a9e02f1a6137a126814b51325130e54c2f9b5c44a988dce46d4e6feb4d (from https://pypi.org/simple/sip-models/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached sip_models-0.1.1.tar.gz (8.6 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Anaconda3\envs\py37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\matev\\AppData\\Local\\Temp\\pip-install-xn6yg43f\\sip-models_35043bee890d45288a830092f457a537\\setup.py'"'"'; __file__='"'"'C:\\Users\\matev\\AppData\\Local\\Temp\\pip-install-xn6yg43f\\sip-models_35043bee890d45288a830092f457a537\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\matev\AppData\Local\Temp\pip-pip-egg-info-p7680r9a'
         cwd: C:\Users\matev\AppData\Local\Temp\pip-install-xn6yg43f\sip-models_35043bee890d45288a830092f457a537\
    Complete output (2 lines):
    error in sip_models setup command: use_2to3 is invalid.
    V3
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/21/ec/4af03266cd9a118996938972e6afb70690c62cbba1b8fef854cb063714f7/sip_models-0.1.1.tar.gz#sha256=134f96e039b67923f30dff8c9cf644a1929711d5b5770c049bcc93aa3b8be306 (from https://pypi.org/simple/sip-models/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached sip_models-0.1.0.tar.gz (5.1 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Anaconda3\envs\py37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\matev\\AppData\\Local\\Temp\\pip-install-xn6yg43f\\sip-models_b8630145699844e582669a97ce6bc959\\setup.py'"'"'; __file__='"'"'C:\\Users\\matev\\AppData\\Local\\Temp\\pip-install-xn6yg43f\\sip-models_b8630145699844e582669a97ce6bc959\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\matev\AppData\Local\Temp\pip-pip-egg-info-tmfq1su7'
         cwd: C:\Users\matev\AppData\Local\Temp\pip-install-xn6yg43f\sip-models_b8630145699844e582669a97ce6bc959\
    Complete output (2 lines):
    error in sip_models setup command: use_2to3 is invalid.
    V3
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/85/54/b07a4876b8589f50532d31e79864a6d88910beab8139cb5cc165929c3c31/sip_models-0.1.0.tar.gz#sha256=34e98fc918f51ffb44e1bb4eb33157553bc7ece8c22186ab0f5b2d17f7de23e0 (from https://pypi.org/simple/sip-models/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement sip_models
ERROR: No matching distribution found for sip_models

**Comment by MatevzKu** [comment]
It would seem that the problem lies in the sip depedency which has an error that prevents it from being built...

**Comment by m-weigand** [comment]
Could you please try to install from git (within the 3.7 environment):

pip install git+https://github.com/m-weigand/sip_models

I removed the arcane call to 2to3 in setup.py

**Comment by MatevzKu** [comment]
Yup, that did it!
Was able to install both tools and they work just fine with my 3.7 code now. Was able to reproduce graphs from my previous experiments.
RESOLVED.
Thanks for a quick reply/support!
